[package]
name = "slay-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe.workspace = true
egui.workspace = true
slay-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
